"""empty message

Revision ID: ab2699ca357d
Revises: 
Create Date: 2021-07-03 19:24:40.430660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab2699ca357d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CT_scan',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('path', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ct_scan')
    op.add_column('feedback', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('feedback', sa.Column('Date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'Date')
    op.drop_column('feedback', 'user_id')
    op.create_table('ct_scan',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('path', mysql.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('CT_scan')
    # ### end Alembic commands ###
